### ISSUE TITLE
Azure: Resource names too long

### ISSUE THREAD

**Issue by adriansuhov** [LIS/LISAv2#460] opened 2018-11-28 13:59 UTC
We encountered issues with the resource names being to long in Azure. The restriction there is that the names of the resources cannot be bigger than 80 chars. We have situations where a resource name (e.g - extraNetworkCard) is bigger than 80 chars and the test fails because of that. We should consider:

- Decrease the number of chars computed here: https://github.com/LIS/LISAv2/blob/master/Libraries/Azure.psm1#L382
- Decrease the chars for $testId computed here: https://github.com/LIS/LISAv2/blob/master/Run-LisaV2.ps1#L100
- Change setupType names to reduce the number of chars

**Comment by chvalean** [comment] 2018-11-28 14:02
$curtime itself has 12 chars, definitely must be trimmed

@juhlee-microsoft for ack, maybe someone from other teams can take this, we have allocated already multiple issues.

**Comment by chvalean** [comment] 2019-01-23 13:09
Closing this as addressed in multiple ways - setupType name change, prefix for RGs has been changed.
Haven't seen any failures recently caused by exceeding this limit.

**Closed by chvalean** 2019-01-23 13:09 UTC
Labels: P0, bug
